services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: clinichub_backend-backend
    container_name: clinic_hub_backend
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:lmS4Kxxb/Dcr2osMA/bQxsBoFD/VrlUxkqWnUvTLNnU=
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=clinic_hub_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=mohammad123
      - SESSION_DRIVER=file
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:18-alpine
    container_name: clinic_hub_database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mohammad123
      - POSTGRES_DB=clinic_hub_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    # driver: local
